"""add is_singleton and needs_human_review columns

Revision ID: 3108d781e859
Revises: 4e822790f73d
Create Date: 2026-03-05 15:16:39.439722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3108d781e859'
down_revision: Union[str, Sequence[str], None] = '4e822790f73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('needs_human_review', sa.Boolean(), nullable=True))
    # keep ix_articles_fts — alembic can't auto-detect custom FTS indexes
    op.add_column('clusters', sa.Column('is_singleton', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'is_singleton')
    op.drop_column('articles', 'needs_human_review')
    # ### end Alembic commands ###
