"""initial schema

Revision ID: 4e822790f73d
Revises: 
Create Date: 2026-03-05 12:02:57.118929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '4e822790f73d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('primary_actors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geographic_scope', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('rss_url', sa.String(length=1000), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('language_code', sa.String(length=5), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('editorial_language', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.Column('is_state_adjacent', sa.Boolean(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_country', 'sources', ['country_code'], unique=False)
    op.create_index('ix_sources_type', 'sources', ['source_type'], unique=False)
    op.create_table('acled_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acled_event_id', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('actors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('source_scale', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['linked_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acled_actors', 'acled_events', ['actors'], unique=False, postgresql_using='gin')
    op.create_index('ix_acled_country', 'acled_events', ['country'], unique=False)
    op.create_index('ix_acled_date', 'acled_events', ['event_date'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('original_language', sa.String(length=50), nullable=True),
    sa.Column('translation_language', sa.String(length=50), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('original_language_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('absence_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_articles_absence_flags', 'articles', ['absence_flags'], unique=False, postgresql_using='gin')
    op.create_index('ix_articles_event', 'articles', ['event_id'], unique=False)
    op.create_index('ix_articles_original_language_terms', 'articles', ['original_language_terms'], unique=False, postgresql_using='gin')
    op.create_index('ix_articles_source', 'articles', ['source_id'], unique=False)
    op.create_index('ix_articles_url', 'articles', ['url'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('geographic_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('centroid_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('attempted', sa.Boolean(), nullable=True),
    sa.Column('retrieved', sa.Boolean(), nullable=True),
    sa.Column('dark_layer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirror_gap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('us_frame', sa.Text(), nullable=True),
    sa.Column('world_frame', sa.Text(), nullable=True),
    sa.Column('delta_score', sa.Float(), nullable=True),
    sa.Column('us_domestic_ratio', sa.Float(), nullable=True),
    sa.Column('us_sources_count', sa.Integer(), nullable=True),
    sa.Column('world_sources_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('primary_frame', sa.Text(), nullable=True),
    sa.Column('frame_confidence', sa.Float(), nullable=True),
    sa.Column('positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('internal_tensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('absence_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unspeakable_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uncertainty_score', sa.Float(), nullable=True),
    sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_absence', 'analyses', ['absence_flags'], unique=False, postgresql_using='gin')
    op.create_index('ix_analyses_internal_tensions', 'analyses', ['internal_tensions'], unique=False, postgresql_using='gin')
    op.create_index('ix_analyses_positions', 'analyses', ['positions'], unique=False, postgresql_using='gin')
    op.create_index('ix_analyses_unspeakable', 'analyses', ['unspeakable_positions'], unique=False, postgresql_using='gin')
    op.create_table('cluster_memberships',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('distance_from_centroid', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'cluster_id')
    )
    op.create_table('llm_council_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('models_agree', sa.Boolean(), nullable=True),
    sa.Column('consensus_frame', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('model_readings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dissent_recorded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # full-text search index on articles.translated_text
    op.execute("""
        CREATE INDEX ix_articles_fts ON articles
        USING gin(to_tsvector('english', COALESCE(translated_text, '')))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_articles_fts")
    op.drop_table('llm_council_verdicts')
    op.drop_table('cluster_memberships')
    op.drop_index('ix_analyses_unspeakable', table_name='analyses', postgresql_using='gin')
    op.drop_index('ix_analyses_positions', table_name='analyses', postgresql_using='gin')
    op.drop_index('ix_analyses_internal_tensions', table_name='analyses', postgresql_using='gin')
    op.drop_index('ix_analyses_absence', table_name='analyses', postgresql_using='gin')
    op.drop_table('analyses')
    op.drop_table('mirror_gap')
    op.drop_table('coverage_gaps')
    op.drop_table('clusters')
    op.drop_index('ix_articles_url', table_name='articles')
    op.drop_index('ix_articles_source', table_name='articles')
    op.drop_index('ix_articles_original_language_terms', table_name='articles', postgresql_using='gin')
    op.drop_index('ix_articles_event', table_name='articles')
    op.drop_index('ix_articles_absence_flags', table_name='articles', postgresql_using='gin')
    op.drop_table('articles')
    op.drop_index('ix_acled_date', table_name='acled_events')
    op.drop_index('ix_acled_country', table_name='acled_events')
    op.drop_index('ix_acled_actors', table_name='acled_events', postgresql_using='gin')
    op.drop_table('acled_events')
    op.drop_index('ix_sources_type', table_name='sources')
    op.drop_index('ix_sources_country', table_name='sources')
    op.drop_table('sources')
    op.drop_table('events')
    # ### end Alembic commands ###
